In [4]:
import numpy
import torch

In [6]:
a = torch.zeros([4, 9])
print(a, a.shape)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]) torch.Size([4, 9])


In [7]:
b = numpy.zeros([5, 3])
print(b, b.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (5, 3)
